server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test
#mybatis-plus:
#  configuration:
#    #打印mybatis-plus的查询语句和结果
#    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl